typography_spectrum: 0.499062264803797
color:
  brandStrength: 0.055895281955599785
  lightness: 0.8870985873509198
  saturation: 0.15721383783966303
  rhythmicContrast: 0.7638579071499407
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.4110658953431994
analytics:
  google: UA-72775510-1
author:
  name: Michael Borell
  email: michaelborell@cryptocurrencyglobalwealth.com
  url: 'http://www.cryptocurrencyglobalwealth.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/29e49c88-4e60-465d-a43b-473799d1f921.png
name: Cryptocurrency Global Wealth
navigation:
  - id: 'http://www.cryptocurrencyglobalwealth.com'
    url: 'http://www.cryptocurrencyglobalwealth.com'
    name: '"Moving Forward"'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0eacf4bf-ee2a-4d8c-bd6e-89d3211a819c.png
