typography_spectrum: 0.277077215956524
color:
  brandStrength: 0.7049952591769397
  lightness: 0.9841301331762224
  saturation: 0.7982312997337431
  rhythmicContrast: 0.13719258084893227
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#2EB2FF'
    - '#6F6F6F'
    - '#343434'
layout_spectrum: 0.5425510306376964
analytics:
  google: UA-72775510-1
author:
  name: Michael Borell
  email: michaelborell@cryptocurrencyglobalwealth.com
  url: 'http://www.cryptocurrencyglobalwealth.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/29e49c88-4e60-465d-a43b-473799d1f921.png
name: Cryptocurrency Global Wealth
navigation:
  - name: '"Your Digital DNA is Here"'
    url: 'http:www.cryptocurrencyglobalwealth.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0eacf4bf-ee2a-4d8c-bd6e-89d3211a819c.png
title: Paving the Future towards a "Trust-less Industry"
