layout_spectrum: 0.36101199709810317
typography_spectrum: 0.20592833310365677
color:
  brandStrength: 0.7893017460592091
  lightness: 0.9802680944558233
  saturation: 0.21707235206849873
  rhythmicContrast: 0.06943400180898607
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
analytics:
  google: UA-72775510-1
  twitter: 'https://twitter.com/MichaelBorell1'
  facebook: 'https://www.facebook.com/CGWBorell/'
author:
  name: Michael Borell
  email: michaelborell@cryptocurrencyglobalwealth.com
  url: 'http://www.cryptocurrencyglobalwealth.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f3d6f21e-0d25-41b5-abcd-d9676c578af5.jpg
name: Cryptocurrency Global Wealth
navigation:
  - name: YOUR DIGITAL DNA
    url: 'http://www.cryptocurrencyglobalwealth.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/94972941-2e9a-44a1-9f86-1abe2867b9a5.jpg
title: The Future in Currency
