typography_spectrum: 0.8519103203434497
color:
  brandStrength: 0.9781417744234204
  lightness: 0.9931812717113644
  saturation: 0.29226326872594655
  rhythmicContrast: 0.5693629519082606
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
layout_spectrum: 0.9222323808353394
analytics:
  google: UA-72775510-1
author:
  name: Michael Borell
  email: michaelborell@cryptocurrencyglobalwealth.com
  url: 'http://www.cryptocurrencyglobalwealth.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/29e49c88-4e60-465d-a43b-473799d1f921.png
name: Cryptocurrency Global Wealth
navigation:
  - id: 'http://www.cryptocurrencyglobalwealth.com'
    url: 'http://www.cryptocurrencyglobalwealth.com'
    name: '"Moving Forward"'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0eacf4bf-ee2a-4d8c-bd6e-89d3211a819c.png
