typography_spectrum: 0.6078695505857468
color:
  brandStrength: 0.8556813460309058
  lightness: 0.8453054269775748
  saturation: 0.8346192119643092
  rhythmicContrast: 0.2505915705114603
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.43342285812832415
analytics:
  google: UA-72775510-1
author:
  name: Michael Borell
  email: michaelborell@cryptocurrencyglobalwealth.com
  url: 'http://www.cryptocurrencyglobalwealth.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/29e49c88-4e60-465d-a43b-473799d1f921.png
name: Cryptocurrency Global Wealth
navigation:
  - name: '"Your Digital DNA is Here"'
    url: 'http:www.cryptocurrencyglobalwealth.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0eacf4bf-ee2a-4d8c-bd6e-89d3211a819c.png
title: Paving the Future towards a "Trust-less Industry"
